### ISSUE TITLE
As a user, I want to be able to delete my account so that I can be dismissed from all the activities of the website.

### ISSUE THREAD

**Issue by bpolatCS** [SU-CS308-22FA/TFF-NationalTeamSelector-Team07#69]
Acceptance Criteria:

1. User must be able to delete his account from the profile page.
2. after deleting the profile, a user should direct to the main page.
3. After deletion of the account, the user has no longer access to the activity he/she created or was involved in

**Comment by bengisuozdemir** [comment]
all tests are satisfied
